name: Python Test

on:
  push:
    branches:
      - dev  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run:
        pip install -e src/

    - name: Run tests
      run: python -m unittest testing/test_myers.py
